version: '3.7'

services:
  app:
    container_name: app
    build: .
    command: npm start
    volumes: 
      - .:/app
      - /app/node_modules
    env_file: 
      - ./src/config/env-vars.js
    ports:
      - 3000:3000